version: 2
source:
  - name: public
    schema: public
    table: 
      - name: tele_data


models:
  - name: tele_data_transfrmation
    description: "telegram data transformation"
    columns:
      - name: channel_title
        type: string
      - name:   channel_username
        type: string
      - name: id
        type: float  
      - name:   messages
        type: string
      - name: date
        type: float
      - name: media_path
        type: double
 
           
 