version: 2
source:
  - name: public
  schema: public
  table: 
    -  name: tele_data


modles:
   - name: tele_data_transfrmation
      description: "telegram data transformation"
      columns:
       - name: channel_title
         data_tests: 
           - not_null
       - name:   channel_username
         data_tests: 
           - not_null
        - name: id
         data_tests: 
           - not_null
       - name:   message
         data_tests: 
           - not_null
